### ISSUE TITLE
Docker networks instead of links

### ISSUE THREAD

**Issue by igomez10** [mozilla/voice-web#1457]
docker links will be removed in the near future, see 
https://docs.docker.com/compose/compose-file/#links and 
https://docs.docker.com/network/links/

The docker-compose.yaml file defines the link from the 'web' service to the 'db' and 's3proxy'. The recommended way, as specified in the docs,  is to define docker networks. These come with hostname resolution, meaning that within the 'web' container it's possible to reach the database via mysql://db:3306 or http://s3proxy:1234.

so...something like this for the docker-compose.yaml
```yaml
services: 
   db: 
       .... 
       networks:
            - voice-web-network
       ....

   s3proxy:
       ....
        networks:
            - voice-web-network
       ....

   web:
      ....
      networks:
            - voice-web-network
      ....

networks:
    voice-web-network
```
